### ISSUE TITLE
Support grpc.reflection.v1alpha.ServerReflection

### ISSUE THREAD

**Issue by K-MTG** [wesky93/grpc_requests#22]
**Is your feature request related to a problem? Please describe.**
I'm trying to send data to OpenTelemetryCollector. I encounter the following solution error
```
        status = StatusCode.UNIMPLEMENTED
        details = "unknown service grpc.reflection.v1alpha.ServerReflection"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-07-31T11:06:03.679704-07:00", grpc_status:12, grpc_message:"unknown service grpc.reflection.v1alpha.ServerReflection"}"

```

**Describe the solution you'd like**
Support GRPC metric messages to OTEL collector.

**Comment by ViridianForge** [comment]
Would you mind putting together an example of your client implementation and how you used the client to get that status and details back? Perhaps as well what server you were using the client to query against?

**Comment by wesky93** [comment]
You probably want to [send the data to OpenTelemetry manually](https://opentelemetry.io/docs/concepts/instrumentation/manual/#export-data).
The problem is that due to the nature of OpenTelemetry, it seems likely that the reflection service is disabled on the collector server. So if you want to use grpc_requests, you'll need to create a stub based on the .proto file [here](https://github.com/open-telemetry/opentelemetry-proto/tree/main/opentelemetry/proto).
Alternatively, you can use the OpenTelemetry SDK instead of grpc_requests.
